### PR TITLE
Add support for custom error messages.

### PR DESCRIPTION
**Pull request by btpoe**
@wraithgar I wanted to run this one by you before we settle on the convention. Doesn't break any of the existing tests.

Let me know what you think.

### CODE REVIEW

**Comment by wraithgar** [comment]
The code makes sense and the test is great.  ^5 on adding a new feature w/o breaking backwards compatibility.

Should probably update the docs in gh-pages after this merges.

**Comment by btpoe** [comment]
Awesome! I'll update gh-pages later today when I have some free time.

**Comment by wraithgar** [comment]
Thanks for doing this, it's a big feature people asked for a lot. ^5

**Comment by btpoe** [comment]
Sure thing. The number of requests was a large reason I decided to tackle it ;)

**Pull request merged**
